//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attend
    {
        public int CId { get; set; }
        public string Name { get; set; }
        public string CEmail { get; set; }
        public string CPhone { get; set; }
        public string Status { get; set; }
    }
}
